name: cancer_ai_detection
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.4

dependencies:
  awesome_extensions: ^2.1.0
  dotted_border: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  font_awesome_flutter: ^10.12.0
  go_router: ^17.1.0
  google_fonts: ^8.0.2
  gp_backend_client:
    git:
      url: https://github.com/YoussefLasheen/gp
      path: gp_backend/gp_backend_client
      ref: d5fe504bffb32cea5d0d99837f65da1feec3a6b9
  http: ^1.6.0
  image_picker: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
